### ISSUE TITLE
Can't compile on ALT Linux

### ISSUE THREAD

**Issue by voodya** [gkv311/occt-samples-gtk#5]
Cascade version 7.6.0, manually installed with all dependencies. There are no errors when building Cmake, but make throws errors like "undefined reference to". Tried specifying cascade package paths, but that doesn't help. What could be the problem?
![Snimok_ekrana_v_2022-04-13_22-21-00](https://user-images.githubusercontent.com/99678480/163399920-2cf4c863-5884-4e78-bcb7-f1bda3c4ebed.png)

**Comment by gkv311** [comment]
Are you sure there is no mixture of OCCT libraries installed in the system (e.g. from system repositories + manual build)? Looks like compiler used one headers (from OCCT 7.6), while linker is trying to link to older libraries (7.5) from the first glance...

**Comment by dinam0n** [comment]
Добрый день! У меня подобная проблема тоже на Альте, хотя пробовали и на Fedora, Astra.  Вывод консоли такой:
dinamon@altfrecad Build $ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dinamon/Projects/occt-gtk-test/Build
dinamon@altfrecad Build $ make -j$(nproc --ignore=1)
[ 66%] Building CXX object CMakeFiles/occt-gtkmm-test.dir/main.cpp.o
[ 66%] Building CXX object CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o
[100%] Linking CXX executable occt-gtkmm-test
ld: CMakeFiles/occt-gtkmm-test.dir/main.cpp.o: в функции «main»:
main.cpp:(.text+0x38): неопределённая ссылка на «OSD::SetSignalStackTraceLength(int)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o: в функции «OcctGtkViewer::onGlAreaRealized()»:
OcctGtkViewer.cxx:(.text+0x3e9c): неопределённая ссылка на «OpenGl_GraphicDriver::InitEglContext(void*, void*, void*)»
ld: OcctGtkViewer.cxx:(.text+0x416c): неопределённая ссылка на «AIS_InteractiveContext::Display(opencascade::handle<AIS_InteractiveObject> const&, int, int, bool, PrsMgr_DisplayStatus)»
ld: OcctGtkViewer.cxx:(.text+0x424b): неопределённая ссылка на «AIS_InteractiveContext::Display(opencascade::handle<AIS_InteractiveObject> const&, int, int, bool, PrsMgr_DisplayStatus)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o: в функции «OcctGtkViewer::onGlAreaReleased()»:
OcctGtkViewer.cxx:(.text+0x47cd): неопределённая ссылка на «V3d_View::Remove()»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV13OcctGtkViewer[_ZTV13OcctGtkViewer]+0x388): неопределённая ссылка на «Aspect_WindowInputListener::update3dMouseTranslation(WNT_HIDSpaceMouse const&)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV13OcctGtkViewer[_ZTV13OcctGtkViewer]+0x390): неопределённая ссылка на «Aspect_WindowInputListener::update3dMouseRotation(WNT_HIDSpaceMouse const&)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV13OcctGtkViewer[_ZTV13OcctGtkViewer]+0x398): неопределённая ссылка на «Aspect_WindowInputListener::update3dMouseKeys(WNT_HIDSpaceMouse const&)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV13OcctGtkViewer[_ZTV13OcctGtkViewer]+0x3a0): неопределённая ссылка на «AIS_ViewController::SelectInViewer(NCollection_Vec2<int> const&, AIS_SelectionScheme)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV13OcctGtkViewer[_ZTV13OcctGtkViewer]+0x3a8): неопределённая ссылка на «AIS_ViewController::SelectInViewer(NCollection_Sequence<NCollection_Vec2<int> > const&, AIS_SelectionScheme)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV13OcctGtkViewer[_ZTV13OcctGtkViewer]+0x3b0): неопределённая ссылка на «AIS_ViewController::UpdateRubberBand(NCollection_Vec2<int> const&, NCollection_Vec2<int> const&)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV13OcctGtkViewer[_ZTV13OcctGtkViewer]+0x410): неопределённая ссылка на «AIS_ViewController::PickAxis(gp_Pnt&, opencascade::handle<AIS_InteractiveContext> const&, opencascade::handle<V3d_View> const&, gp_Ax1 const&)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV21Standard_NoSuchObject[_ZTV21Standard_NoSuchObject]+0x40): неопределённая ссылка на «Standard_Failure::GetStackString() const»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV21Standard_NoSuchObject[_ZTV21Standard_NoSuchObject]+0x48): неопределённая ссылка на «Standard_Failure::SetStackString(char const*)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV19Standard_OutOfRange[_ZTV19Standard_OutOfRange]+0x40): неопределённая ссылка на «Standard_Failure::GetStackString() const»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV19Standard_OutOfRange[_ZTV19Standard_OutOfRange]+0x48): неопределённая ссылка на «Standard_Failure::SetStackString(char const*)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV19Standard_RangeError[_ZTV19Standard_RangeError]+0x40): неопределённая ссылка на «Standard_Failure::GetStackString() const»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV19Standard_RangeError[_ZTV19Standard_RangeError]+0x48): неопределённая ссылка на «Standard_Failure::SetStackString(char const*)»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV20Standard_DomainError[_ZTV20Standard_DomainError]+0x40): неопределённая ссылка на «Standard_Failure::GetStackString() const»
ld: CMakeFiles/occt-gtkmm-test.dir/OcctGtkViewer.cxx.o:(.data.rel.ro._ZTV20Standard_DomainError[_ZTV20Standard_DomainError]+0x48): неопределённая ссылка на «Standard_Failure::SetStackString(char const*)»
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/occt-gtkmm-test.dir/build.make:116: occt-gtkmm-test] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/occt-gtkmm-test.dir/all] Ошибка 2
make: *** [Makefile:91: all] Ошибка 2
В системе стоит OpenCascade 7.5, я ему в CMakeLists указываю использовать вручную скомпилированную версию 7.6
[CMakeLists.txt](https://github.com/gkv311/occt-samples-gtk/files/8857803/CMakeLists.txt)

**Comment by gkv311** [comment]
```.diff
+set(OpenCASCADE_INCLUDE_myDIR "OCCT/include/opencascade/")
+set(OpenCASCADE_LIBRARY_myDIR "OCCT/lin64/gcc/lib")
```
Почему здесь указаны относительные пути, вместо ожидаемых абсолютных?

```.diff
-find_package (OpenCASCADE REQUIRED)
+#find_package (OpenCASCADE REQUIRED)
```
Почему эта строка закомментирована?

```.diff
-set (CMAKE_CXX_STANDARD 11)
+set (CMAKE_CXX_STANDARD 23)
```
Зачем для сборки проекта используется другая версия C++ стандарта?

**Comment by dinam0n** [comment]
> 

Спасибо большое!  Прописал абсолютные пути, всё отлично! остальные параметры уже менял в качестве эксперимента... Стыдоба)))  будем учиться...
